# -------------------------------- dev-环境 -----------------------------------

# 设置当前模块服务名称
spring:
  application:
    name: auth-server


# 设置启动端口号
server:
  port: 48081
  servlet:
    context-path: /api/auth


--- # 配置spring-data-redis
spring:
  redis:
    host:
    port:
    password:
    database: 0
    jedis:
      pool:
        enabled: true
        max-active: 32
        max-idle: 16
        min-idle: 4


--- # 配置sentinel信息
spring:
  cloud:
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719


# 配置dubbo信息
dubbo:
  application:
    name: dubbo-${spring.application.name}
  protocol:
    port: -1
    name: dubbo
    threads: 400
    threadpool: cached
    dispatcher: message
  registry:
    address: nacos://
    parameters:
      namespace: 64e29a8b-edd7-4f60-b941-24111fb1081c
  # parameters.register-consumer-url: true
  # 设置消费者超时时间为3秒
  consumer:
    timeout: 10000



# 定义有关jwt的配置
filesbottle:
  jwt:
    enabled: true   # 是否开启JWT登录认证功能
    secret: filesbottlefilesbottlefilesbottlefilesbottlefilesbottlefilesbottlefilesbottlefilesbottlefilesbottle  # JWT 私钥，用于校验JWT令牌的合法性
    expiration: 3600000 # JWT 令牌的有效期，用于校验JWT令牌的合法性，一个小时
    header: Authorization # (注意：该参数需要与common模块-TokenConstants中的令牌标识对应) HTTP 请求的 Header 名称，该 Header作为参数传递 JWT 令牌
    userParamName: userId  # 用户登录认证用户名参数名称
    pwdParamName: password  # 用户登录认证密码参数名称
    oneRefreshToken: true # 是否为一次性地刷新令牌
    multipleRefreshToken: 2 # 刷新令牌有效期为单位有效期的倍数（2，表示为2 * expiration）



# 设置日志文件名称、日志配置文件路径
logging:
  config: classpath:logback-dev.xml
logback:
  file:
    path: ${user.home}/FilesBottleDev_Logs/${spring.application.name}

