# -------------------------------- dev-环境 -----------------------------------
# 设置当前模块服务名称
spring:
  application:
    name: ffmpeg-server


# 设置启动端口号
server:
  port: 48086
  servlet:
    context-path: /api/ffmpeg


custom:
  ip: 


--- # 设置 nacos discovery ip 地址
spring:
  cloud:
    nacos:
      discovery:
        ip: 



# 在生产环境中进行部署的时候需要进行指定、运行 jar 包 (nginx ip + 端口号)
nginx:
  address: ${custom.ip}:5000


ffmpeg:
  neturl: http://${nginx.address}/hlsvideo/
  path: /usr/bin/ffmpeg
  filepath: /home/travis/hlsvideo/



--- # 修改上传文件大小的限制
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


--- # 配置sentinel信息
spring:
  cloud:
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: :8858
        port: 8719


# 配置dubbo信息
dubbo:
  application:
    name: dubbo-${spring.application.name}
  protocol:
    port: 20880
    name: dubbo
    threads: 200
    threadpool: cached
    dispatcher: message
  registry:
    address: nacos://:8848?username=nacos&password=nacos
    parameters:
      namespace: 64e29a8b-edd7-4f60-b941-24111fb1081c
  # parameters.register-consumer-url: true
  # 设置消费者超时时间为3秒
  consumer:
    timeout: 10000



# 设置日志文件名称、日志配置文件路径
logging:
  config: classpath:logback-pro.xml

logback:
  file:
    path: ${user.home}/FilesBottleDev_Logs/${spring.application.name}
