# -------------------------------- dev-环境 -----------------------------------
# 设置当前模块服务名称
spring:
  application:
    name: knife4j-server


# 设置启动端口号
server:
  port: 48079
  servlet:
    context-path: /knife4j



# 设置日志文件名称、日志配置文件路径
logging:
  config: classpath:logback-dev.xml

logback:
  file:
    path: ${user.home}/FilesBottleDev_Logs/${spring.application.name}


# 设置 knife4j（基于nacos）
knife4j:
  enable-aggregation: true
  nacos:
    enable: true
    service-url: http://:8848/nacos
    routes:
      - name: 权限认证服务
        serviceName: auth-server
#        groupName: auth
        # dev命名空间
        namespaceId: 64e29a8b-edd7-4f60-b941-24111fb1081c
        location: /api/auth/v2/api-docs?group=default
        swaggerVersion: 2.0
        servicePath: /
      - name: 文档服务
        serviceName: document-server
#        groupName: document
        # dev命名空间
        namespaceId: 64e29a8b-edd7-4f60-b941-24111fb1081c
        location: /api/document/v2/api-docs?group=default
        swaggerVersion: 2.0
        servicePath: /
      - name: 人员及团队管理服务
        serviceName: member-server
        #        groupName: document
        # dev命名空间
        namespaceId: 64e29a8b-edd7-4f60-b941-24111fb1081c
        location: /api/member/v2/api-docs?group=default
        swaggerVersion: 2.0
        servicePath: /
